#
# qdipole conda build metadata
#

# NOTE: scipy is installed during the build to assure a compatible version
#       of the Fortran compiler and its run-time libraries.
#       conda is not able to resolve version conflicts if the scipy and qdipole
#       are compiled with different versions of the GFortran compiler.

{% set version = "0.5.0" %}

package:
  name: "qdipole"
  version: {{ version }}

source:
  git_rev: {{ "qdipole-" + version }}
  git_url: "https://github.com/ESA-VirES/MagneticModel"

requirements:
  build:
   - make
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}
   - scipy

test:
  commands:
    - ls -l $PREFIX/share/qdipole/
    - run_dipole_test "" "$PREFIX/share/qdipole"

about:
  home: https://github.com/ESA-VirES/MagneticModel/
