#
# qdipole conda build metadata
#

# NOTE: scipy is installed during the build to assure a compatible version
#       of the Fortran compiler and its run-time libraries.
#       conda is not able to resolve version conflicts if the scipy and qdipole
#       are compiled with different versions of the GFortran compiler.

{% set version = "0.5.0" %}

package:
  name: "qdipole"
  version: {{ version }}

source:
  git_rev: {{ "qdipole-" + version }}
  git_url: "https://github.com/ESA-VirES/MagneticModel"

requirements:
  build:
   - make
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}
   - scipy

test:
  commands:
    - ls -l $PREFIX/share/qdipole/
    - cd $PREFIX/share/qdipole/
    - qdlatlon_test apexsh_1995-2015.txt | diff - test_result.qdlatlon.apexsh_1995-2015.txt
    - qdlatlon_test apexsh_1980-2020.txt | diff - test_result.qdlatlon.apexsh_1980-2020.txt
    - qdlatlon_test apexsh_1980-2025.txt | diff - test_result.qdlatlon.apexsh_1980-2025.txt
    - qdlatlon_test apexsh_1980-2030.txt | diff - test_result.qdlatlon.apexsh_1980-2030.txt
    - mlt_test | diff - test_result.mlt.txt
    - subsol_test | diff - test_result.subsol.txt

about:
  home: https://github.com/ESA-VirES/MagneticModel/
