#
# CDF library conda build metadata
#

# NOTE: scipy is installed during the build to assure a compatible version
#       of the Fortran compiler and its run-time libraries.
#       conda is not able to resolve version conflicts if the scipy and libcdf
#       are compiled with different versions of the GFortran compiler.


{% set version = "3.8.1" %}
{% set file_version = "cdf38_1" %}

package:
  name: "cdf"
  version: {{ version }}

source:
  - url: https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/{{ file_version }}/unix/{{ file_version }}-dist-cdf.tar.gz
    sha256: 8d8b2d8238516c892c60e60e96272106341b306c09b397094bc8d4192bbcfa64

requirements:
  build:
   - make
   - {{ compiler('c') }}
   - {{ compiler('fortran') }}
   - ncurses
   - scipy

about:
  home: https://github.com/ESA-VirES/MagneticModel/
