name: CI
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.10'
          - python: '3.11'
          - python: '3.12'
          - python: '3.13'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Get packages
        run: |
          python3 --version
          sudo apt-get install gfortran
          sudo apt-get install libhdf5-dev
      - name: Install
        run: |
          ( cd libcdf && make build && sudo make install )
          ( cd qdipole && ./configure && make build && sudo make install && make test )
          pip3 install --upgrade pip
          pip3 install wheel
          pip3 install numpy
          pip3 install scipy
          pip3 install spacepy
          pip3 install ./eoxmagmod/
      - name: Scripts
        run: |
          pip3 list
          mkdir -p ./test && cd ./test
          pip3 show -f eoxmagmod
          python3 -c 'import eoxmagmod' && python3 -m unittest discover -p '[a-z]*.py' -v eoxmagmod
  notification:
    runs-on: ubuntu-latest
    permissions: {}
    needs: testing
    steps:
      # send Slack notifications
      - name: action-slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Workflow ${{ github.workflow }} completed with status: ${{ needs.testing.result }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Repo:* ${{ github.repository }}\n*Commit:* ${{ github.sha }}\n*Author:* ${{ github.actor }}\n*Ref:* ${{ github.ref }}\n*Status:* ${{ needs.testing.result }}"
