name: CI
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.10'
          - python: '3.11'
          - python: '3.12'
          - python: '3.13'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Get packages
        run: |
          python3 --version
          sudo apt-get install gfortran
          sudo apt-get install libhdf5-dev
      - name: Install
        run: |
          ( cd libcdf && make build && sudo make install )
          ( cd qdipole && ./configure && make build && sudo make install && make test )
          pip3 install --upgrade pip
          pip3 install wheel
          pip3 install numpy
          pip3 install scipy
          pip3 install spacepy
          pip3 install ./eoxmagmod/
      - name: Scripts
        run: |
          pip3 list
          mkdir -p ./test && cd ./test
          pip3 show -f eoxmagmod
          python3 -c 'import eoxmagmod' && python3 -m unittest discover -p '[a-z]*.py' -v eoxmagmod
  notification:
    runs-on: ubuntu-latest
    permissions: {}
    needs: testing
    steps:
      # send Slack notifications to the eox organization
      - name: action-slack
        uses: 8398a7/action-slack@59b127a91e89ce70980e1bc926dca351ad0a1b32
        with:
          status: ${{ needs.testing.result }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
